### ISSUE TITLE
Recommended way to generate and preview the site

### ISSUE THREAD

**Issue by chbw** [horstjens/internationalopenmagazine#7]
It would be nice to have a recommended/documented/automated/standard way of generating the site and running a local server for site preview. This would have two benefits. First, it lowers the barrier for potential contributors who, like me, have neither heard of pelican nor actually used python before. Second, automating the site generation results in reproducible output which, for example, makes it easier to discuss issues like #6.

**Comment by horstjens** [comment]
i created https://github.com/horstjens/internationalopenmagazine/blob/master/localinstall.md
